name       : zmusic
version    : 1.1.3
release    : 2
source     :
    - https://github.com/coelckers/ZMusic/archive/1.1.3.tar.gz : 5f432b022e023175eae7701625f79287e9ffe889a444179681381026b4fb93bf
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : GZDoom's music system as a standalone library
description: |
    GZDoom's music system as a standalone library
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fluidsynth)
    - pkgconfig(libmpg123)
    - pkgconfig(sndfile)
setup      : |
    %cmake_ninja \
        -DDYN_FLUIDSYNTH=OFF \
        -DDYN_MPG123=OFF \
        -DDYN_SNDFILE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
