name       : zmusic
version    : 1.1.2
release    : 1
source     :
    - https://github.com/coelckers/ZMusic/archive/1.1.2.tar.gz : 951940fe63ee386fdea044f2543c7460977921ce3e60d282b87be81546078e07
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : GZDoom's music system as a standalone library
description: |
    GZDoom's music system as a standalone library
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fluidsynth)
    - pkgconfig(libmpg123)
    - pkgconfig(sndfile)
setup      : |
    %cmake_ninja \
        -DDYN_FLUIDSYNTH=OFF \
        -DDYN_MPG123=OFF \
        -DDYN_SNDFILE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
