name       : zmusic
version    : 1.1.6
release    : 4
source     :
    - https://github.com/coelckers/ZMusic/archive/refs/tags/1.1.6.tar.gz : 2cc4a08c4d213df80743828538631f452e1858c2ea5bb47a616e221492de05c0
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : GZDoom's music system as a standalone library
description: |
    GZDoom's music system as a standalone library
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fluidsynth)
    - pkgconfig(libmpg123)
    - pkgconfig(sndfile)
setup      : |
    %cmake_ninja \
        -DDYN_FLUIDSYNTH=OFF \
        -DDYN_MPG123=OFF \
        -DDYN_SNDFILE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
